siteTitle='Datenbank-Dokumentation      Zimmerbelegung'
baseColor = "#884499"
linkPrefix = "/gastbyDpc"
docPages = [
"/docs/datenbank/",
"/docs/gast-tabelle/",
"/docs/zimmer-tabelle/",
"/docs/status-tabelle/",
"/docs/buchungen-tabelle/",
"/docs/fragestellungen/",
]
