#+PROPERTY: tangle "./documentation.sql"
#+OPTIONS: toc:nil num:nil
#+HTML: <title>Datenbank</title>
#+PROPERTY: header-args :engine mysql :dbuser root :dbpassword root :results silent

* Erstellen und auswählen der Datenbank *hotelbuchung*
#+BEGIN_SRC sql
CREATE DATABASE IF NOT EXISTS hotelbuchung;
USE hotelbuchung;
#+END_SRC
Als erstes legt man die Datenbank auf dem Server an und wählt sie zur Benutzung aus.
Der Zusatz ~IF NOT EXISTS~ dient dazu, bei wiederholender Ausführung Fehler zu vermeiden, falls die jeweiligen Objekte bereits erstellt wurden.
Zur Löschung der Datenbank kann man ~DROP DATABASE hotelbuchung~ verwenden.
* Befüllen der Datenbank
Nun befüllt man die Datenbank mit mehreren Tabellen, welche Attribute besitzen, mittels des ~CREATE~-Befehls.
Im selben Schritt definiert man auch die Primär- und Fremdschlüssel, um die Beziehungen zwischen den Tabellen darzustellen. Außerdem legt man fest was passieren soll, wenn ein Objekt gelöscht wird. Die Attribute bekommen einen Typ zugewiesen, welcher zum Beispiel festlegt, wie viele Zeichen gespeichert werden können.
* Befüllen der Tabellen
Anschließend werden die Tabellen jeweils mit Testdaten befüllt.
Dazu wird der ~INSERT~-Befehl genutzt.
Man muss nur die Tabelle mit ihren Spalten definieren und Werte hinzufügen. Die Id's zählen automatisch hoch, da ~AUTO_INCREMENT~ gesetzt ist.
