#+BEGIN_HTML
<title> Aufgabenstellung </title>
#+END_HTML
[[http://bit.ly/1O7ztaX]]

2. Zimmerbelegung

2.1. Situationsbeschreibung

Die Reservierungs- und Belegungsverwaltung der Hotelzimmer erfolgt derzeit über MS-Excel- und MS-Word-Da-teien, welche auf einem lokalen Server gespeichert sind. Die Dateneingabe und -pflege erfolgt durch die Mitarbeiter an verschiedenen PCs. Zusätzlich muss eine Übersicht der Reservierungen und Belegungen in Kalenderform für die einzelnen Hotelzimmer manuell erstellt und gepflegt werden.

2.2. Problembeschreibung

Bei der Dateneingabe und -pflege kommt es immer wieder zu dem Problem, dass die Dateien auf anderen PCs be-reits geöffnet sind und bei Änderungen lokal auf dem PC gespeichert werden müssen. Dies führt dazu, dass die Än-derungen nachträglich von den Mitarbeitern abgeglichen werden. Aufgrund der aktuellen Arbeitsabläufe werden Reservierungen und Belegungen nicht immer zeitnah eingetragen, was zu der Gefahr führt, dass Reservierungen doppelt oder mit Überschneidungen vorgenommen werden.

Fragestellungen

* Welche Zimmer sind "reserviert“, „belegt“ oder für eine Reservierung „gesperrt“?

* Wieviel Tage ist ein Zimmer in Folge „reserviert“ oder „belegt“?

* Welche Zimmer sind ab besten oder am schlechtesten im Monat ausgelastet?
